<option value="">Pick...</option>
<option value="bi bi-fire">Fire</option>
<option value="bi bi-basket2">Basket</option>
<option value="bi bi-check">Check</option>
<option value="bi bi-check-circle">Check Circle</option>
<option value="bi bi-circle">Circle</option>
<option value="bi bi-circle-fill">Circle Filled</option>
<option value="bi bi-stars">Stars</option>
<option value="bi bi-droplet">Droplet</option>
<option value="bi bi-cup-hot">Hot Cup</option>
<option value="bi bi-flower1">Flower 1</option>
<option value="bi bi-flower2">Flower 2</option>
<option value="bi bi-brightness-high">Brightness/Sun</option>
<option value="bi bi-hand-index">Hand Pointing</option>
<option value="bi bi-arrow-right">Right Arrow</option>
<option value="bi bi-layers">Layers</option>
<option value="bi bi-alarm">Alarm/Timer</option>
<option value="bi bi-heart-pulse">Heart Pulse</option>
<option value="bi bi-star-fill">Star Filled</option>
<option value="bi bi-info-circle">Info</option>
<option value="bi bi-box">Box</option>
<option value="bi bi-box-seam">Box Seam</option>
